-- seed: countries (ISO 3166-1)
-- Source: ISO 3166-1 alpha-3 / numeric codes (assigned list, 2024-2025)
-- Spanish names: Wikipedia ES / RAE canonical short forms
-- Sorted by iso_a3
INSERT INTO public.countries (iso_a3, iso_numeric, name_en, name_es) VALUES
  ('ABW', 533, 'Aruba', 'Aruba'),
  ('AFG', 4, 'Afghanistan', 'Afganistán'),
  ('AGO', 24, 'Angola', 'Angola'),
  ('AIA', 660, 'Anguilla', 'Anguila'),
  ('ALA', 248, 'Åland Islands', 'Islas Åland'),
  ('ALB', 8, 'Albania', 'Albania'),
  ('AND', 20, 'Andorra', 'Andorra'),
  ('ARE', 784, 'United Arab Emirates', 'Emiratos Árabes Unidos'),
  ('ARG', 32, 'Argentina', 'Argentina'),
  ('ARM', 51, 'Armenia', 'Armenia'),
  ('ASM', 16, 'American Samoa', 'Samoa Americana'),
  ('ATA', 10, 'Antarctica', 'Antártida'),
  ('ATF', 260, 'French Southern Territories', 'Territorios Australes Franceses'),
  ('ATG', 28, 'Antigua and Barbuda', 'Antigua y Barbuda'),
  ('AUS', 36, 'Australia', 'Australia'),
  ('AUT', 40, 'Austria', 'Austria'),
  ('AZE', 31, 'Azerbaijan', 'Azerbaiyán'),
  ('BDI', 108, 'Burundi', 'Burundi'),
  ('BEL', 56, 'Belgium', 'Bélgica'),
  ('BEN', 204, 'Benin', 'Benín'),
  ('BES', 535, 'Bonaire, Sint Eustatius and Saba', 'Bonaire, San Eustaquio y Saba'),
  ('BFA', 854, 'Burkina Faso', 'Burkina Faso'),
  ('BGD', 50, 'Bangladesh', 'Bangladés'),
  ('BGR', 100, 'Bulgaria', 'Bulgaria'),
  ('BHR', 48, 'Bahrain', 'Baréin'),
  ('BHS', 44, 'Bahamas', 'Bahamas'),
  ('BIH', 70, 'Bosnia and Herzegovina', 'Bosnia y Herzegovina'),
  ('BLM', 652, 'Saint Barthélemy', 'San Bartolomé'),
  ('BLR', 112, 'Belarus', 'Bielorrusia'),
  ('BLZ', 84, 'Belize', 'Belice'),
  ('BMU', 60, 'Bermuda', 'Bermudas'),
  ('BOL', 68, 'Bolivia', 'Bolivia'),
  ('BRA', 76, 'Brazil', 'Brasil'),
  ('BRB', 52, 'Barbados', 'Barbados'),
  ('BRN', 96, 'Brunei', 'Brunéi'),
  ('BTN', 64, 'Bhutan', 'Bután'),
  ('BVT', 74, 'Bouvet Island', 'Isla Bouvet'),
  ('BWA', 72, 'Botswana', 'Botsuana'),
  ('CAF', 140, 'Central African Republic', 'República Centroafricana'),
  ('CAN', 124, 'Canada', 'Canadá'),
  ('CCK', 166, 'Cocos (Keeling) Islands', 'Islas Cocos'),
  ('CHE', 756, 'Switzerland', 'Suiza'),
  ('CHL', 152, 'Chile', 'Chile'),
  ('CHN', 156, 'China', 'China'),
  ('CIV', 384, 'Côte d''Ivoire', 'Costa de Marfil'),
  ('CMR', 120, 'Cameroon', 'Camerún'),
  ('COD', 180, 'Democratic Republic of the Congo', 'República Democrática del Congo'),
  ('COG', 178, 'Republic of the Congo', 'República del Congo'),
  ('COK', 184, 'Cook Islands', 'Islas Cook'),
  ('COL', 170, 'Colombia', 'Colombia'),
  ('COM', 174, 'Comoros', 'Comoras'),
  ('CPV', 132, 'Cabo Verde', 'Cabo Verde'),
  ('CRI', 188, 'Costa Rica', 'Costa Rica'),
  ('CUB', 192, 'Cuba', 'Cuba'),
  ('CUW', 531, 'Curaçao', 'Curazao'),
  ('CXR', 162, 'Christmas Island', 'Isla de Navidad'),
  ('CYM', 136, 'Cayman Islands', 'Islas Caimán'),
  ('CYP', 196, 'Cyprus', 'Chipre'),
  ('CZE', 203, 'Czechia', 'Chequia'),
  ('DEU', 276, 'Germany', 'Alemania'),
  ('DJI', 262, 'Djibouti', 'Yibuti'),
  ('DMA', 212, 'Dominica', 'Dominica'),
  ('DNK', 208, 'Denmark', 'Dinamarca'),
  ('DOM', 214, 'Dominican Republic', 'República Dominicana'),
  ('DZA', 12, 'Algeria', 'Argelia'),
  ('ECU', 218, 'Ecuador', 'Ecuador'),
  ('EGY', 818, 'Egypt', 'Egipto'),
  ('ERI', 232, 'Eritrea', 'Eritrea'),
  ('ESH', 732, 'Western Sahara', 'Sáhara Occidental'),
  ('ESP', 724, 'Spain', 'España'),
  ('EST', 233, 'Estonia', 'Estonia'),
  ('ETH', 231, 'Ethiopia', 'Etiopía'),
  ('FIN', 246, 'Finland', 'Finlandia'),
  ('FJI', 242, 'Fiji', 'Fiyi'),
  ('FLK', 238, 'Falkland Islands', 'Islas Malvinas'),
  ('FRA', 250, 'France', 'Francia'),
  ('FRO', 234, 'Faroe Islands', 'Islas Feroe'),
  ('FSM', 583, 'Micronesia', 'Micronesia'),
  ('GAB', 266, 'Gabon', 'Gabón'),
  ('GBR', 826, 'United Kingdom', 'Reino Unido'),
  ('GEO', 268, 'Georgia', 'Georgia'),
  ('GGY', 831, 'Guernsey', 'Guernsey'),
  ('GHA', 288, 'Ghana', 'Ghana'),
  ('GIB', 292, 'Gibraltar', 'Gibraltar'),
  ('GIN', 324, 'Guinea', 'Guinea'),
  ('GLP', 312, 'Guadeloupe', 'Guadalupe'),
  ('GMB', 270, 'Gambia', 'Gambia'),
  ('GNB', 624, 'Guinea-Bissau', 'Guinea-Bisáu'),
  ('GNQ', 226, 'Equatorial Guinea', 'Guinea Ecuatorial'),
  ('GRC', 300, 'Greece', 'Grecia'),
  ('GRD', 308, 'Grenada', 'Granada'),
  ('GRL', 304, 'Greenland', 'Groenlandia'),
  ('GTM', 320, 'Guatemala', 'Guatemala'),
  ('GUF', 254, 'French Guiana', 'Guayana Francesa'),
  ('GUM', 316, 'Guam', 'Guam'),
  ('GUY', 328, 'Guyana', 'Guyana'),
  ('HKG', 344, 'Hong Kong', 'Hong Kong'),
  ('HMD', 334, 'Heard Island and McDonald Islands', 'Islas Heard y McDonald'),
  ('HND', 340, 'Honduras', 'Honduras'),
  ('HRV', 191, 'Croatia', 'Croacia'),
  ('HTI', 332, 'Haiti', 'Haití'),
  ('HUN', 348, 'Hungary', 'Hungría'),
  ('IDN', 360, 'Indonesia', 'Indonesia'),
  ('IMN', 833, 'Isle of Man', 'Isla de Man'),
  ('IND', 356, 'India', 'India'),
  ('IOT', 86, 'British Indian Ocean Territory', 'Territorio Británico del Océano Índico'),
  ('IRL', 372, 'Ireland', 'Irlanda'),
  ('IRN', 364, 'Iran', 'Irán'),
  ('IRQ', 368, 'Iraq', 'Irak'),
  ('ISL', 352, 'Iceland', 'Islandia'),
  ('ISR', 376, 'Israel', 'Israel'),
  ('ITA', 380, 'Italy', 'Italia'),
  ('JAM', 388, 'Jamaica', 'Jamaica'),
  ('JEY', 832, 'Jersey', 'Jersey'),
  ('JOR', 400, 'Jordan', 'Jordania'),
  ('JPN', 392, 'Japan', 'Japón'),
  ('KAZ', 398, 'Kazakhstan', 'Kazajistán'),
  ('KEN', 404, 'Kenya', 'Kenia'),
  ('KGZ', 417, 'Kyrgyzstan', 'Kirguistán'),
  ('KHM', 116, 'Cambodia', 'Camboya'),
  ('KIR', 296, 'Kiribati', 'Kiribati'),
  ('KNA', 659, 'Saint Kitts and Nevis', 'San Cristóbal y Nieves'),
  ('KOR', 410, 'South Korea', 'Corea del Sur'),
  ('KWT', 414, 'Kuwait', 'Kuwait'),
  ('LAO', 418, 'Laos', 'Laos'),
  ('LBN', 422, 'Lebanon', 'Líbano'),
  ('LBR', 430, 'Liberia', 'Liberia'),
  ('LBY', 434, 'Libya', 'Libia'),
  ('LCA', 662, 'Saint Lucia', 'Santa Lucía'),
  ('LIE', 438, 'Liechtenstein', 'Liechtenstein'),
  ('LKA', 144, 'Sri Lanka', 'Sri Lanka'),
  ('LSO', 426, 'Lesotho', 'Lesoto'),
  ('LTU', 440, 'Lithuania', 'Lituania'),
  ('LUX', 442, 'Luxembourg', 'Luxemburgo'),
  ('LVA', 428, 'Latvia', 'Letonia'),
  ('MAC', 446, 'Macao', 'Macao'),
  ('MAF', 663, 'Saint Martin (French part)', 'San Martín (parte francesa)'),
  ('MAR', 504, 'Morocco', 'Marruecos'),
  ('MCO', 492, 'Monaco', 'Mónaco'),
  ('MDA', 498, 'Moldova', 'Moldavia'),
  ('MDG', 450, 'Madagascar', 'Madagascar'),
  ('MDV', 462, 'Maldives', 'Maldivas'),
  ('MEX', 484, 'Mexico', 'México'),
  ('MHL', 584, 'Marshall Islands', 'Islas Marshall'),
  ('MKD', 807, 'North Macedonia', 'Macedonia del Norte'),
  ('MLI', 466, 'Mali', 'Malí'),
  ('MLT', 470, 'Malta', 'Malta'),
  ('MMR', 104, 'Myanmar', 'Birmania'),
  ('MNE', 499, 'Montenegro', 'Montenegro'),
  ('MNG', 496, 'Mongolia', 'Mongolia'),
  ('MNP', 580, 'Northern Mariana Islands', 'Islas Marianas del Norte'),
  ('MOZ', 508, 'Mozambique', 'Mozambique'),
  ('MRT', 478, 'Mauritania', 'Mauritania'),
  ('MSR', 500, 'Montserrat', 'Montserrat'),
  ('MTQ', 474, 'Martinique', 'Martinica'),
  ('MUS', 480, 'Mauritius', 'Mauricio'),
  ('MWI', 454, 'Malawi', 'Malaui'),
  ('MYS', 458, 'Malaysia', 'Malasia'),
  ('MYT', 175, 'Mayotte', 'Mayotte'),
  ('NAM', 516, 'Namibia', 'Namibia'),
  ('NCL', 540, 'New Caledonia', 'Nueva Caledonia'),
  ('NER', 562, 'Niger', 'Níger'),
  ('NFK', 574, 'Norfolk Island', 'Isla Norfolk'),
  ('NGA', 566, 'Nigeria', 'Nigeria'),
  ('NIC', 558, 'Nicaragua', 'Nicaragua'),
  ('NIU', 570, 'Niue', 'Niue'),
  ('NLD', 528, 'Netherlands', 'Países Bajos'),
  ('NOR', 578, 'Norway', 'Noruega'),
  ('NPL', 524, 'Nepal', 'Nepal'),
  ('NRU', 520, 'Nauru', 'Nauru'),
  ('NZL', 554, 'New Zealand', 'Nueva Zelanda'),
  ('OMN', 512, 'Oman', 'Omán'),
  ('PAK', 586, 'Pakistan', 'Pakistán'),
  ('PAN', 591, 'Panama', 'Panamá'),
  ('PCN', 612, 'Pitcairn Islands', 'Islas Pitcairn'),
  ('PER', 604, 'Peru', 'Perú'),
  ('PHL', 608, 'Philippines', 'Filipinas'),
  ('PLW', 585, 'Palau', 'Palaos'),
  ('PNG', 598, 'Papua New Guinea', 'Papúa Nueva Guinea'),
  ('POL', 616, 'Poland', 'Polonia'),
  ('PRI', 630, 'Puerto Rico', 'Puerto Rico'),
  ('PRK', 408, 'North Korea', 'Corea del Norte'),
  ('PRT', 620, 'Portugal', 'Portugal'),
  ('PRY', 600, 'Paraguay', 'Paraguay'),
  ('PSE', 275, 'Palestine', 'Palestina'),
  ('PYF', 258, 'French Polynesia', 'Polinesia Francesa'),
  ('QAT', 634, 'Qatar', 'Catar'),
  ('REU', 638, 'Réunion', 'Reunión'),
  ('ROU', 642, 'Romania', 'Rumania'),
  ('RUS', 643, 'Russia', 'Rusia'),
  ('RWA', 646, 'Rwanda', 'Ruanda'),
  ('SAU', 682, 'Saudi Arabia', 'Arabia Saudita'),
  ('SDN', 729, 'Sudan', 'Sudán'),
  ('SEN', 686, 'Senegal', 'Senegal'),
  ('SGP', 702, 'Singapore', 'Singapur'),
  ('SGS', 239, 'South Georgia and the South Sandwich Islands', 'Islas Georgias del Sur y Sandwich del Sur'),
  ('SHN', 654, 'Saint Helena, Ascension and Tristan da Cunha', 'Santa Elena, Ascensión y Tristán de Acuña'),
  ('SJM', 744, 'Svalbard and Jan Mayen', 'Svalbard y Jan Mayen'),
  ('SLB', 90, 'Solomon Islands', 'Islas Salomón'),
  ('SLE', 694, 'Sierra Leone', 'Sierra Leona'),
  ('SLV', 222, 'El Salvador', 'El Salvador'),
  ('SMR', 674, 'San Marino', 'San Marino'),
  ('SOM', 706, 'Somalia', 'Somalia'),
  ('SPM', 666, 'Saint Pierre and Miquelon', 'San Pedro y Miquelón'),
  ('SRB', 688, 'Serbia', 'Serbia'),
  ('SSD', 728, 'South Sudan', 'Sudán del Sur'),
  ('STP', 678, 'São Tomé and Príncipe', 'Santo Tomé y Príncipe'),
  ('SUR', 740, 'Suriname', 'Surinam'),
  ('SVK', 703, 'Slovakia', 'Eslovaquia'),
  ('SVN', 705, 'Slovenia', 'Eslovenia'),
  ('SWE', 752, 'Sweden', 'Suecia'),
  ('SWZ', 748, 'Eswatini', 'Esuatini'),
  ('SXM', 534, 'Sint Maarten (Dutch part)', 'San Martín (parte neerlandesa)'),
  ('SYC', 690, 'Seychelles', 'Seychelles'),
  ('SYR', 760, 'Syria', 'Siria'),
  ('TCA', 796, 'Turks and Caicos Islands', 'Islas Turcas y Caicos'),
  ('TCD', 148, 'Chad', 'Chad'),
  ('TGO', 768, 'Togo', 'Togo'),
  ('THA', 764, 'Thailand', 'Tailandia'),
  ('TJK', 762, 'Tajikistan', 'Tayikistán'),
  ('TKL', 772, 'Tokelau', 'Tokelau'),
  ('TKM', 795, 'Turkmenistan', 'Turkmenistán'),
  ('TLS', 626, 'Timor-Leste', 'Timor Oriental'),
  ('TON', 776, 'Tonga', 'Tonga'),
  ('TTO', 780, 'Trinidad and Tobago', 'Trinidad y Tobago'),
  ('TUN', 788, 'Tunisia', 'Túnez'),
  ('TUR', 792, 'Türkiye', 'Turquía'),
  ('TUV', 798, 'Tuvalu', 'Tuvalu'),
  ('TWN', 158, 'Taiwan', 'Taiwán'),
  ('TZA', 834, 'Tanzania', 'Tanzania'),
  ('UGA', 800, 'Uganda', 'Uganda'),
  ('UKR', 804, 'Ukraine', 'Ucrania'),
  ('UMI', 581, 'United States Minor Outlying Islands', 'Islas Ultramarinas Menores de Estados Unidos'),
  ('URY', 858, 'Uruguay', 'Uruguay'),
  ('USA', 840, 'United States', 'Estados Unidos'),
  ('UZB', 860, 'Uzbekistan', 'Uzbekistán'),
  ('VAT', 336, 'Vatican City', 'Ciudad del Vaticano'),
  ('VCT', 670, 'Saint Vincent and the Grenadines', 'San Vicente y las Granadinas'),
  ('VEN', 862, 'Venezuela', 'Venezuela'),
  ('VGB', 92, 'British Virgin Islands', 'Islas Vírgenes Británicas'),
  ('VIR', 850, 'United States Virgin Islands', 'Islas Vírgenes de los Estados Unidos'),
  ('VNM', 704, 'Vietnam', 'Vietnam'),
  ('VUT', 548, 'Vanuatu', 'Vanuatu'),
  ('WLF', 876, 'Wallis and Futuna', 'Wallis y Futuna'),
  ('WSM', 882, 'Samoa', 'Samoa'),
  ('YEM', 887, 'Yemen', 'Yemen'),
  ('ZAF', 710, 'South Africa', 'Sudáfrica'),
  ('ZMB', 894, 'Zambia', 'Zambia'),
  ('ZWE', 716, 'Zimbabwe', 'Zimbabue');
